/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2019-06-15 07:29:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import sdlc.*;

public final class no3_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

    /* No.1 :  Java代码藏于 JSP 中，与 html混合，这是JSP的特征，实验 1， 我们将一些字符串赋予java变量，然后看下面如何应用   Line 65*/
    String title="流浪地球";
    /* No.2 :  Java代码藏于 JSP 中，与 html混合，这是JSP的特征，实验 1， 我们将一些字符串从本project的一个Javaclass中获取后，赋予一个java变量，然后看下面如何应用 Line 70   */
	HelloWorldWeb poem=new HelloWorldWeb();
    String poemText=poem.getPoemContent();

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<style>\r\n");
      out.write(".background1 {\r\n");
      out.write("\tbackground-image: url(/static/imgs/pic001.jpg);\r\n");
      out.write("\tbackground-color: #000000;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("\tfunction run(clickedObj) {\r\n");
      out.write("\t\t$(\"#firstline\").fadeOut('slow');\r\n");
      out.write("\t\t$('#intr')[0].pause();\r\n");
      out.write("\t\t$('#poem')[0].play();\r\n");
      out.write("\t\t$('#poem-txt').fadeIn('slow');\r\n");
      out.write("\t\t$(clickedObj).animate({\r\n");
      out.write("\t\t\twidth : '10px',\r\n");
      out.write("\t\t\topacity : '0.2',\r\n");
      out.write("\t\t\tleft : '1800px',\r\n");
      out.write("\t\t\ttop : '100px'\r\n");
      out.write("\t\t}, 30000);\r\n");
      out.write("\t\t//$('#waiting')[0].play();\r\n");
      out.write("\t\t$(\"#moviebox\").show('slow');\r\n");
      out.write("\t\t$(\"#movie\")[0].play();\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction onVideoEnd(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#moviebox\").fadeOut('slow');\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#hornor\").fadeIn('slow');\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('#poem-txt').fadeOut('slow');\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('#poem-txt').animate({\r\n");
      out.write("\t\t\tbottom : '100px',\r\n");
      out.write("\t\t\tright : '100px'\r\n");
      out.write("\t\t}, 18000);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('#waiting')[0].play();\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction onWaitingAudioEnd(){\r\n");
      out.write("\t\t$('#intr')[0].play();\t\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>The Wandering Earth</title>\r\n");
      out.write("<script src=\"/static/jquery.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"background1\">\r\n");
      out.write("\t<audio id=\"intr\" controls=\"controls\"\r\n");
      out.write("\t\tsrc=\"/static/audio/introduction.mp3\" autoplay=\"autoplay\"></audio>\r\n");
      out.write("    <a href=\"/\" style=\"font-size:30px\" >回到主页</a>\r\n");
      out.write("\t<audio id=\"poem\" src=\"/static/audio/wanderingEarch-poem.mp3\"\r\n");
      out.write("\t\tpreload=\"auto\"></audio>\r\n");
      out.write("\t<span id=\"firstline\" style=\"font-size: 22px; color: white\">大家好，我与这学期学习“软件工程导论”的学生们准备设计和实现一个“<span\r\n");
      out.write("\t\tstyle=\"font-size: 38px; color: red\">");
      out.print(title );
      out.write("</span>”的模拟工程！ 欢迎大家观赏,谢谢！点击屏幕左下角的地球，可以开始悲壮的流浪！！\r\n");
      out.write("\t</span>\r\n");
      out.write("\t<audio id=\"waiting\" src=\"/static/audio/waiting.mp3\" preload=\"auto\" onended=\"onWaitingAudioEnd();\"></audio>\r\n");
      out.write("\t<div id=\"poem-txt\"\r\n");
      out.write("\t\tstyle=\"display: none; font-size: 22px; color: orange; position:absolute; left :10px;top:50px\" >\r\n");
      out.write("\t\t");
      out.print(poemText);
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<img src=\"/static/imgs/earth.png\"\r\n");
      out.write("\t\tstyle=\"position: absolute; left: 10px; bottom: 10px; width: 200px\"\r\n");
      out.write("\t\tonclick=\"run(this);return false\" \r\n");
      out.write("\t\ttitle=\"点击后，开始流浪 ！\"\r\n");
      out.write("\t\t/>\r\n");
      out.write("\t<div id=\"moviebox\" style=\"margin-top: 100px; display: none\"\r\n");
      out.write("\t\talign=\"center\">\r\n");
      out.write("\t\t<video id=\"movie\" height=\"500px\" controls=\"controls\"\r\n");
      out.write("\t\t\tsrc=\"/static/video/movie.mp4\" onended=\"onVideoEnd();\" />\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"hornor\" style=\"display:none;position:absolute;left:300px; bottom:10px;color:white;font-size:24px\" align=\"center\">谨以此向今年的电影《流浪地球》和华为公司在 2019 年发生的事表示致敬 !  本网页将放在以下网站 sdlc.huaku-2019.xyz (华为公司的云服务器) </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
